version: "3.9"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=SvaneveienNR1
      - GF_SERVER_ROOT_URL=http://grafana.local/
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - overlay-observability
    deploy:
      replicas: 1

networks:
  overlay-observability:
    external: true

volumes:
  grafana-data:

